#!/bin/bash

sudo rm -r ~/.config/i3/
sudo cp -r ~/Documents/Backup/i3 ~/.config/i3
sudo rm -r ~/.config/polybar 
sudo cp -r ~/Documents/Backup/polybar ~/.config/polybar
sudo rm ~/.config/nvim/init.vim
sudo cp ~/Documents/Backup/nvim ~/.config/nvim/init.vim
